version: 3.2
services:
  coffee-shop:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  database:
    image:
      mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=r00t
